// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Ohc-NJK1zn8QZ-ELT4Bi077Uk7jOiKU',
    appId: '1:281211180526:web:6cb1028b92c7958ac5eaff',
    messagingSenderId: '281211180526',
    projectId: 'skillradar-b5774',
    authDomain: 'skillradar-b5774.firebaseapp.com',
    storageBucket: 'skillradar-b5774.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Ohc-NJK1zn8QZ-ELT4Bi077Uk7jOiKU',
    appId: '1:281211180526:android:67e9f9c611b204fcc5eaff',
    messagingSenderId: '281211180526',
    projectId: 'skillradar-b5774',
    storageBucket: 'skillradar-b5774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOn_hRYZQBK-f4KzQUNqYQN0yvGabDu5c',
    appId: '1:281211180526:ios:b0e31fdf80d97fd6c5eaff',
    messagingSenderId: '281211180526',
    projectId: 'skillradar-b5774',
    storageBucket: 'skillradar-b5774.firebasestorage.app',
    iosBundleId: 'com.anduin.aiSkillRadar',
  );
}
